# Generated by Django 3.1.5 on 2021-01-11 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210109_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='teacherName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='className',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lesson'),
        ),
    ]
